name: Deploy to seenode

on:
  push:
    branches:
      - main 

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Debug API Key (Partial)
          env:
            SEENODE_API_KEY: ${{ secrets.SEENODE_API_KEY }}
          run: echo "API Key starts with: $(echo $SEENODE_API_KEY | cut -c1-5)****"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send HTTP POST request to seenode API
        run: |
          curl -X POST "https://api.seenode.com/v1/applications/${{ secrets.SEENODE_APPLICATION_ID }}/deployments-new" \
            -H "Authorization: Bearer ${{ secrets.SEENODE_JWT_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "gitCommitSha": "${{ github.sha }}"
                }'