name: Deploy to seenode

on:
  push:
    branches:
      - main 

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Debug API Key (Partial)
          run: echo "API Key starts with: $(echo ${{ secrets.SEENODE_API_KEY }} | cut -c1-5)****"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send HTTP POST request to seenode API
        run: |
          curl -X POST "https://api.seenode.com/v1/applications/971517/deployments-new" \
            -H "Authorization: Bearer 82f2e2e3d6105e1a942759a52cef5a9578f6f819d70924300027634e6ac52997" \
            -H "Content-Type: application/json" \
            -d '{
                  "gitCommitSha": "${{ github.sha }}"
                }'